# Preface {.unnumbered}

This quarto book contains the following:

### Part: General

This part of the book contains chapters with general information. The following chapters are available:

1.  [Posit Infrastructure at VI](quarto_files/part_general/posit_infrastructure_at_VI.qmd)

## Part: Configurations

This part of the book contains chapters to help set up various aspects in R, RStudio desktop or Workbench. The following chapters are available:

1.  [Setting up your \$HOME Variable on Windows 10](quarto_files/part_configrations/setting_home_dir.qmd)
2.  [Connecting RStudio to GitHub](quarto_files/part_configrations/connecting_r_studio_to_github)

### Part: R/RStudio Tutorials

This part of the book contains tutorials for a variety of aspects in R/RStudio. The following chapters are available:

1.  [Anatomy of a R package](quarto_files/part_r_rstudio_tutorials/anatomy_of_a_r_package.qmd)
2.  [Projects in RStudio](quarto_files/part_r_rstudio_tutorials/projects_in_r_studio.qmd)
3.  [Parallelization on Workbench](quarto_files/part_r_rstudio_tutorials/parallelization_on_workbench.qmd)
4.  [Getting Help with R](quarto_files/part_r_rstudio_tutorials/getting_help_with_r.qmd)
5.  [RStudio Tips and Tricks](quarto_files/part_r_rstudio_tutorials/r_studio_tips_and_tricks.qmd)

### Part: Posit Connect

This part of the book contains tutorials that will help you to work with Posit Connect server. The following chapters are available:

1.  [Creating Pins on Connect](quarto_files/part_posit_connect/creating_pins_on_connect.qmd)
2.  [Git Backed Deployment to Posit Connect](quarto_files/part_posit_connect/git_backed_deployment_to_posit_connect.qmd)

To contribute to this book, please read [Contributing](quarto_files/contributing.qmd).
